#!/opt/perl/bin/perl

use 5.010;
use warnings;
use strict;
use autodie;

use CPAN::Package;
use Cwd             qw/abs_path/;

my $Conf = CPAN::Package->new(
    perl        => "/opt/perl/bin/perl",
    perlpkg     => "/packages/All/opt-perl-5.16.3.txz",

    dist        => abs_path("dist"),
    packages    => abs_path("pkg"),

    su          => sub { 
        system "sudo", @_;
    },
);

my $jail = $Conf->find(Jail => "91R-amd64");

$jail->start;
$jail->add_initial_pkgs;

for my $mod (@ARGV) {
    my $dist        = $Conf->find(Dist => $mod);
    $dist->fetch;

    my $build       = $Conf->build_for($jail, $dist);
    $build->unpack_dist;
    $build->read_meta("META");

    my $req         = $build->needed("configure");
    for (@{ $$req{needed} }) {
        say "===> INSTALL [$_]";
    }

    $build->configure_dist;
    $build->read_meta("MYMETA");

    $req            = $build->needed("build");
    for (@{ $$req{needed} }) {
        say "===> INSTALL [$_]";
    }

    $build->make_dist($_) for qw/build test install/;
    $build->fixup_install;

    my $dest        = $build->destdir;
    $jail->injail($dest, "find", ".");
    $jail->injail($dest, "sh", "-c",
        "find . -name .packlist | xargs cat");
}

$jail->stop;
