---
abstract: 'Build OS packages from CPAN distributions'
author:
  - 'Copyright 2013 Ben Morrow <ben@morrow.me.uk>.'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Package
provides:
  App::cpan2pkg:
    file: lib/App/cpan2pkg.pm
  CPAN::Package:
    file: lib/CPAN/Package.pm
    version: '4'
  CPAN::Package::Base:
    file: lib/CPAN/Package/Base.pm
  CPAN::Package::Build:
    file: lib/CPAN/Package/Build.pm
  CPAN::Package::Dist:
    file: lib/CPAN/Package/Dist.pm
  CPAN::Package::Dist::CPAN:
    file: lib/CPAN/Package/Dist/CPAN.pm
  CPAN::Package::Dist::Git:
    file: lib/CPAN/Package/Dist/Git.pm
  CPAN::Package::Exception:
    file: lib/CPAN/Package/Exception.pm
  CPAN::Package::Jail:
    file: lib/CPAN/Package/Jail.pm
  CPAN::Package::PkgDB:
    file: lib/CPAN/Package/PkgDB.pm
  CPAN::Package::PkgTool:
    file: lib/CPAN/Package/PkgTool.pm
requires:
  CPAN::Meta: '0'
  CPAN::Meta::Requirements: '2.122'
  Capture::Tiny: '0.20'
  Class::Load: '0'
  DBD::SQLite: '1.39'
  DBI: '0'
  File::Find::Rule: '0'
  File::Find::Rule::DirectoryEmpty: '0'
  File::Slurp: '9999.17'
  HTTP::Tiny: '0'
  List::MoreUtils: '0.33'
  Makefile::Parser: '0'
  Module::Metadata: '0'
  Parse::CPAN::Meta: '0'
  Scope::Guard: '0'
  Try::Tiny: '0'
  YAML::XS: '0'
  parent: '0'
  perl: '5.012000'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Package
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/mauzo/CPAN-Package
version: '4'
